spring:
  redis:
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数 （若使用负数表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 #连接池最大空闲连接数
        min-idle: 0 #连接池最小空闲连接数
    host: 172.31.18.179
    port: 6379
    password: jeemes
    timeout: 36000ms
